#![warn(missing_docs)]
#![cfg_attr(feature="clippy", feature(plugin))]
#![cfg_attr(feature="clippy", plugin(clippy))]
//! An experimental implementation of various
//! [IPFS](https://github.com/ipfs/ipfs)-related components.

#[macro_use]
extern crate log;

extern crate openssl;
extern crate protobuf;
extern crate byteorder;
extern crate rand;
extern crate multiaddr;
extern crate rust_base58;

pub mod crypto;
pub mod net;

// This was generated by protoc and rust-protobuf. Eventually, generating
// proto.rs during the cargo build instead of including it in the repo
// should be investigated.
// Protobuf messages.
#[allow(missing_docs)]
#[cfg_attr(feature="clippy", allow(clippy))]
#[cfg_attr(rustfmt, rustfmt_skip)]
pub mod proto;
